include: package:lints/recommended.yaml

analyzer:
  exclude: 
    - build/**
    - lib/src/openssl.dart
  language:
    strict-casts: true

linter:
  rules:
    - prefer_double_quotes
    - cancel_subscriptions
