name: spake2plus
description: A Dart library for SPAKE2+ protocol
version: 1.0.0
repository: https://github.com/scenee/spake2plus_dart

environment:
  sdk: ^3.5.3

dependencies:
  ffi: ^2.1.3
  path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  ffigen: ^16.0.0
  yaml: ^3.1.3
